### PR TITLE
Generalized add_risk_meters script

### PR DESCRIPTION
**Pull request by jaredkalmus**
The current script requires code changes to be operational and has a lot of custom code that looks like it was built for a single use case. I generalized the script by stripping it down to just accepting a name and query string. Also added an end of script completion message.
script_run
RM_creation
risk_meter

### CODE REVIEW

**Review by lindambrown — COMMENTED** [review]
historical=false needs to stay there until engineering changes false to be the default. I can't remember if that is done yet. The other stuff was there to server as samples because q can't handle everything that people want to build into risk meters. Are you going to document those somewhere else? This script was never meant to work without modification.

**Comment by jaredkalmus** [comment]
@lindambrown What if we left the other examples as comments in the code? My thinking is that the base form of the script should cover the most common use cases so most people could use the script without modification. As it exists today I don't think anybody could make use of the script without modification

**Comment by jaredkalmus** [comment]
Also I don't see historical documented for the create risk meter endpoint. It's listed for the update endpoint which makes sense as sometimes the user may want to retain the historical data in some cases but wipe it in others. https://apidocs.kennasecurity.com/reference#create-asset-group-and-risk-meter

**Comment by jaredkalmus** [comment]
I'll close this one since the changes aren't in-line with the original intent of the script

**Pull request closed without merging**
